### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by takeda-chiaki-53b** [takeda-chiaki-53b/graduation_app_development#39]
### 概要

- MVPリリースまでの実装予定の内容です。
- 現状ストーリーポイント：109ポイント （×2=見積時間： 218時間）です。

### 実装予定の機能

- [ ] 新規登録機能
- [ ] ログイン・ログアウト機能
- [ ] 投稿一覧機能
- [ ] 投稿作成機能
- [ ] 投稿編集機能
- [ ] 投稿削除機能
- [ ] 権限による画面の出し分け
- [ ] brand_adminとsite_admin(自分)権限のみ：ブランド管理者用マイページ機能
- [ ] brand_adminとsite_admin(自分)権限のみ：商品登録機能（一旦商品名のみ）
- [ ] brand_adminとsite_admin(自分)権限のみ：登録済商品一覧機能
- [ ] ブランド検索機能

### 必要なページ

- [ ] トップページ（仮）
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] ログイン前ヘッダー、ログイン後ヘッダー
- [ ] フッター
- [ ] 投稿一覧ページ
- [ ] 投稿作成ページ
- [ ] 投稿編集ページ
- [ ] ブランド管理者用マイページ
- [ ] 商品登録ページ
- [ ] 登録商品一覧ページ
- [ ] 商品詳細ページ
- [ ] 検索ページ
- [ ] ブランド一覧ページ
- [ ] 検索結果一覧ページ

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/2b38fbea-0205-4883-9f7e-ae6141f2081e)

Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態での再提出をお願いいたします。

**Comment by takeda-chiaki-53b** [comment]
ご連絡ありがとうございます。
ご指摘いただいた画面にてプロジェクトが表示されるように修正し、表示確認済です。
お手数ですが、ご確認のほどよろしくお願いします。

---

リポジトリを開いた際にProjectsに表示させるためには「Link a project」を押下し、設定をしなければ表示されないようでした。
確認不足でお手数をお掛けし申し訳ありません。


![Image](https://github.com/user-attachments/assets/b223db0a-ff74-4436-805e-030c3496b8ec)

**Comment by rdhdchloe** [comment]
ありがとうございます。
確認できました。LGTM！

**Comment by takeda-chiaki-53b** [comment]
ありがとうございます！
